Included: 
Excluded:
- '*.csproj'
- '*.prquantifier'
- package-lock.json
- '*.md'
- '*.sln'
- '*.mustache'
- '*.txt'
GitOperationType:
- Add
- Delete
Thresholds:
- GitOperationType:
  - Add
  - Delete
  Value: 50
  Label: XSS
  Color: Green
  Formula: Sum
- GitOperationType:
  - Add
  - Delete
  Value: 100
  Label: SS
  Color: Green
  Formula: Sum
- GitOperationType:
  - Add
  - Delete
  Value: 200
  Label: Medium
  Color: DarkYellow
  Formula: Sum
- GitOperationType:
  - Add
  - Delete
  Value: 400
  Label: Large
  Color: Red
  Formula: Sum
- GitOperationType:
  - Add
  - Delete
  Value: 1000
  Label: Extra Large
  Color: Red
  Formula: Sum
LanguageOptions:
  IgnoreSpaces: true
  IgnoreComments: true
  IgnoreCodeBlockSeparator: true
DynamicBehaviour: false
IgnoreRenamed: true
IgnoreCopied: true
